#!/usr/bin/env bash

# Function to handle signals and clean up before exiting
cleanup() {
    echo "Cleaning up and terminating"
    rm /var/run/holbertonscript.pid
    exit
}

# Trap SIGQUIT and SIGTERM signals and call the cleanup function
trap cleanup SIGQUIT SIGTERM

# Function to handle SIGINT signal
ctrl_c() {
    echo "Y U no love me?!"
}

# Trap SIGINT signal and call ctrl_c function
trap ctrl_c INT

# Create PID file
echo $$ > /var/run/holbertonscript.pid

# Infinite loop
while true; do
    echo "To infinity and beyond"
    sleep 2
done

